/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/Alert.vue')['default']
    AppBar: typeof import('./src/components/Navigation/AppBar.vue')['default']
    Authenticated: typeof import('./src/components/Layout/Authenticated.vue')['default']
    BaseForm: typeof import('./src/components/Form/BaseForm.vue')['default']
    BtnDialog: typeof import('./src/components/Common/Dialog/BtnDialog.vue')['default']
    Default: typeof import('./src/components/Layout/Default.vue')['default']
    Dialog: typeof import('./src/components/Common/Dialog/Dialog.vue')['default']
    FieldWrapper: typeof import('./src/components/Form/FieldWrapper.vue')['default']
    Heading: typeof import('./src/components/Heading/Heading.vue')['default']
    InputField: typeof import('./src/components/Form/InputField.vue')['default']
    Loader: typeof import('./src/components/Common/Loader.vue')['default']
    Profile: typeof import('./src/components/Layout/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Common/Section.vue')['default']
    SelectField: typeof import('./src/components/Form/SelectField.vue')['default']
    Sidebar: typeof import('./src/components/Navigation/Sidebar.vue')['default']
    SprintTable: typeof import('./src/components/Common/SprintTable.vue')['default']
    Table: typeof import('./src/components/Common/Table.vue')['default']
    TextareaField: typeof import('./src/components/Form/TextareaField.vue')['default']
    UserTable: typeof import('./src/components/Common/UserTable.vue')['default']
  }
}
