/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AppBar: (typeof import("./src/components/Navigation/AppBar.vue"))["default"];
    Authenticated: (typeof import("./src/components/Layout/Authenticated.vue"))["default"];
    BaseForm: (typeof import("./src/components/Form/BaseForm.vue"))["default"];
    Default: (typeof import("./src/components/Layout/Default.vue"))["default"];
    Dialog: (typeof import("./src/components/Common/Dialog.vue"))["default"];
    FieldWrapper: (typeof import("./src/components/Form/FieldWrapper.vue"))["default"];
    Heading: (typeof import("./src/components/Heading/Heading.vue"))["default"];
    HelloWorld: (typeof import("./src/components/HelloWorld.vue"))["default"];
    InputField: (typeof import("./src/components/Form/InputField.vue"))["default"];
    MainLayout: (typeof import("./src/components/Layout/MainLayout.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Section: (typeof import("./src/components/Common/Section.vue"))["default"];
    SelectField: (typeof import("./src/components/Form/SelectField.vue"))["default"];
    Sidebar: (typeof import("./src/components/Navigation/Sidebar.vue"))["default"];
    Table: (typeof import("./src/components/Common/Table.vue"))["default"];
  }
}
